### ISSUE TITLE
[Feature request] bind up/down arrows to taskbar menu search results list immediately in search field

### ISSUE THREAD

**Issue by rkitover** [lxqt/lxqt-panel#1799] opened 2022-07-23 01:17 UTC
**Is your feature request related to a problem? Please describe.**
When I search in the taskbar search field, for example for "editor", I have to press the up arrow twice for focus to even switch to the results list, and three times to go up from the focused search result.

**Describe the solution you'd like**
When there is a results list, arrow keys should be forwarded to it immediately from the search input field.

**Describe eventual alternatives you've considered**
Pressing the up arrow twice or using the mouse.

#### Context
This would work more like the taskbar search in Windows and KDE.

**Comment by tsujan** [comment] 2022-07-23 02:20
Duplicate of https://github.com/lxqt/lxqt/issues/1401

**Closed by tsujan** 2022-07-23 02:20 UTC
Labels: duplicate
