### ISSUE TITLE
High CPU load in case of QT_SCALE_FACTOR > 1

### ISSUE THREAD

**Issue by smirnovskysaha** [lxqt/lxqt-panel#1926] opened 2023-08-18 08:40 UTC
**Problem**
lxqt-panel loads CPU heavily when QT_SCALE_FACTOR is not equal to 1.

**Steps to reproduce**
run "QT_SCALE_FACTOR=1.5 lxqt-panel", CPU usage by lxqt-panel becomes about 70%.

**Version**
current (commit 9918a0ec613fe2e48314ad626d1961468a66a820).

**Source of the problem and possible fix**
I have found that the problem goes away when the TaskBar widget is removed from the panel.
Profiling with gprof shows that `LXQtTaskBar::onWindowChanged()`, `LXQtTaskGroup::regroup()`, `LXQtTaskGroup::onWindowChanged()` are called very often in case of QT_SCALE_FACTOR>1.
I have commented out the line 64
```connect(parent, &LXQtTaskBar::refreshIconGeometry, this, &LXQtTaskGroup::refreshIconsGeometry);```
in the file *plugin-taskbar/lxqttaskgroup.cpp* and the problem disappears.

* Distribution: gentoo
* Qt Version: 5.15.10
* liblxqt Version: 1.3.0

**Comment by tsujan** [comment] 2023-08-18 09:06
Not reproducible here, whether I used `QT_SCALE_FACTOR=1.5 lxqt-panel`, or I set the scaling to 1.5 in LXQt Session Settings and log out and in. In both cases, the CPU usage was normal (minimal). In the first case, it made no difference whether I launched apps from Panel, or by using shortcuts.

So, there should be another factor. I'll keep this open for a while, hoping that you might find that factor.

**Comment by tsujan** [comment] 2023-08-18 09:26
Oops! I'd tested with my old laptop, which didn't have the latest git. With my work laptop and the latest git lxqt-panel, I confirm that the CPU usage is high (~20% here).

The cause may be in a recent commit.

**Comment by tsujan** [comment] 2023-08-18 11:19
The cause is that the X11-based function `LXQtTaskButton::refreshIconGeometry` doesn't consider the scale factor. More precisely, the scale factor isn't considered in its argument `geom`.

This is a new behavior (as I mentioned above, it didn't happen in older versions of lxqt-panel). I guess it's caused by a change or bug in `KWindowSystem`. My concern is that if we "fix" it in lxqt-panel and the change/bug is reversed in `KWindowSystem`, we'll have the same problem later. On the other hand, it's a serious problem and should be fixed/avoided.

**Comment by smirnovskysaha** [comment] 2023-08-18 11:56
Ok, thank you for your feedback!
As a workaround, I will comment out the connection with LXQtTaskBar::refreshIconGeometry() in LXQtTaskGroup and will monitor behaviour of lxqt-panel. What possible problems might arise in this case?

**Comment by tsujan** [comment] 2023-08-18 12:15
> What possible problems might arise in this case?

I'm not sure — never dealt with this function before. Perhaps misplaced icons under special circumstances.

**Comment by tsujan** [comment] 2023-08-18 13:26
The KDE doc says that `NETWinInfo::setIconGeometry` sets the icon geometry for the application window. I don't understand why it's needed. Can't Qt do it (whatever it is), independently of X11?

I tested with 1.2.1 in my old laptop by removing `LXQtTaskButton::refreshIconGeometry`. With or without it, the taskbar icons weren't updated when I changed the position of Panel (from bottom to left); I had to restart it to have a usable taskbar after changing the position.

@smirnovskysaha
Do you see a problem in the taskbar if you add a `return;` to the beginning of the function `LXQtTaskButton::refreshIconGeometry` (instead of commenting out the connection to the signal `LXQtTaskBar::refreshIconGeometry`)?

**Comment by smirnovskysaha** [comment] 2023-08-18 13:54
@tsujan 
If I add `return` to the beginning of the function `LXQtTaskButton::refreshIconGeometry` then problem with high CPU load goes away.

**Comment by tsujan** [comment] 2023-08-18 14:26
@smirnovskysaha, thanks!

> Also I have no visible problems in the taskbar.

I don't see any either, whether with git or with an older version. The behavior of icons are also the same when I change the panel's height/width or the icon size of the taskbar (suboptimal).

**Comment by smirnovskysaha** [comment] 2023-08-18 14:42
But I should notice that just adding `return` in `LXQtTaskButton::refreshIconGeometry` leads anyway to multiple calling of `LXQtTaskButton::refreshIconGeometry` (according to profiling information).

**Comment by tsujan** [comment] 2023-08-18 14:57
Yes. Here the signal `LXQtTaskBar::refreshIconGeometry` is emitted continuously. That may be a design flaw, but it doesn't cause an extra CPU usage when `LXQtTaskButton::refreshIconGeometry` is removed.

**Closed** 2023-08-28 07:23 UTC
Labels: bug, upstream
