### ISSUE TITLE
Quick Launch: icons might be replaced after restarting panel if there are other config files

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lxqt-panel#1822] opened 2022-10-08 16:56 UTC
Steps to reproduce
1: drag and drop a script (like for example `fast.sh`) in the quick launch
2: move it as first icon from the left
3: reboot the computer

Result
The first icon in the quick launch is the icon of the file-manager (by clicking on it, not the script will be executed, but the file-manager will appear).

Expectation
The first icon from the left in the quick launch should still be the script-icon.

System
My LXQt 0.17.0 is old although I use Lubuntu 22.04. If the issue does not appear in LXQt 1.1.0 any more, then I’m sorry for this report.

**Comment by tsujan** [comment] 2022-10-08 17:39
Not reproducible.

**Comment by ralf3u** [comment] 2022-10-21 21:10
>Not reproducible.

I don't agree. It is still reproducible in Lubuntu 22.10 with LXQt 1.1.0.

@tsujan 
Could you please reopen this issue?

**Comment by ralf3u** [comment] 2022-10-21 21:24
When the script-icon is placed as second icon from the left (first icon is PCManFM-qt-icon), then the script-icon will disappear after a reboot.

**Comment by tsujan** [comment] 2022-10-21 22:06
> It is still reproducible in Lubuntu 22.10 with LXQt 1.1.0.

It may be (I don't have 1.1.0), but it isn't reproducible here with the latest git version, which will be released as 1.2.0 soon.

**Comment by tsujan** [comment] 2022-10-21 22:15
Since I don't remember any git commit about it in the last 6 months, there's also another possibility: the bug may still exist but the necessary conditions for its appearance may be more than what you described. I'll take a look at the code later...

**Comment by tsujan** [comment] 2022-10-21 23:56
OK, a complicated problem exists in the code, which can appear in different ways to different users, depending on several factors; it can also be invisible to most users. What's described in this report is only a simple example among many, while no other user may be able to reproduce it (in that way). It's very elusive!

The conditions required for triggering the bug aren't simple. What fallows is a rough description.

 1. There should be more than one `panel.conf`, one inside `~/.config/lxqt/` and the other inside another acceptable path, like `/etc/xdg/lxqt`.
 2. Supposing that there are two instances of `panel.conf`, they should have the same section for "quicklaunch". For example, they should both have `[quicklaunch2]` or `[quicklaunch3]` or...
 3. They should have two different values for `apps\n\` (n = 1 or 2 or...), one a desktop file and the other a script name.

Then the code will replace the script with the desktop file when the panel is restarted, because it reads both config files and gives priority to the desktop file (in `LXQtQuickLaunch::LXQtQuickLaunch`).

Of course, other combinations are also possible. It doesn't need to be about the first or second icon; everything depends on the contents of the second config file.

I'm still not sure whether the problem is in `PluginSettings::readArray` or in `LXQtQuickLaunch::LXQtQuickLaunch`.

**Closed** 2022-10-25 08:34 UTC
Labels: bug
