### ISSUE TITLE
Minor main menu up/down arrow navigation issues

### ISSUE THREAD

**Issue by isf63** [lxqt/lxqt-panel#1889] opened 2023-04-20 13:30 UTC
Two minor navigation issues when using the up/down arrows on main menu.

##### Expected Behavior
1. Upon first opening main menu, pressing the up arrow key deselects the search bar and selects the bottom-most menu entry
2. Pressing the up/down arrows never deselects the search bar when a search bar query returns zero results 

##### Current Behavior
1. Up arrow has to be pressed twice to select the bottom-most menu entry
2. Pressing up or down arrows (possibly twice) deselects search bar 

##### Steps to Reproduce (for bugs)
1a. Freshly open the main menu 
1b. Press up arrow once

2a. Enter input into the main menu search bar that returns zero results
2b. Press the up arrow twice or down arrow once

##### Context
Minor issues with keyboard navigation

##### System Information
* LXQt Version: git latest
* Distribution & Version: Arch Linux, 6.2.11-arch1-1
* Qt Version: 5.15.9
* liblxqt Version: git latest

**Comment by tsujan** [comment] 2023-04-20 13:57
Duplicate of the old report https://github.com/lxqt/lxqt/issues/1401

**Closed by tsujan** 2023-04-20 13:57 UTC
