### ISSUE TITLE
Urgent window hint stuck on desktopswitch plugin after corresponding window vanishes before being focused

### ISSUE THREAD

**Issue by M4he** [lxqt/lxqt-panel#1917] opened 2023-07-23 06:52 UTC
##### Expected Behavior

After a window that had an urgent window hint (`NET::DemandsAttention`) set on it vanishes without ever being focused/activated, the urgent marker on the corresponding desktopswitch button should reset.

##### Current Behavior

When a window vanishes that had an urgent hint on it and triggered the corresponding desktopswitch button urgent state, without the window ever being focused/activated, the urgent state of the corresponding desktopswitch button is stuck.

![screenshot-5e636fb6](https://github.com/lxqt/lxqt-panel/assets/1408105/8aae19fa-569b-4aa0-bb57-1d6bf6854a47)

The above screenshot shows lxqt-panel with the desktopswitch plugin, using the "KDE-Plasma" LXQt theme and 5 virtual desktops configured. Desktop 1 and 5 have urgency hints but none of those two desktops has any window with an urgency hint anymore that can be focused to clear the hint. Thus, desktop 1 and 5 are stuck in this highlighted state until lxqt-panel is restarted.

##### Possible Solution

My guess is that the current function responsible for updating the urgency hint:

https://github.com/lxqt/lxqt-panel/blob/04c1a4406a388eeb48b0335ab49137eed6b4aa00/plugin-desktopswitch/desktopswitch.cpp#L118-L133

only reacts to changes of the urgency hint as emitted from the window state itself. However it does not seem to catch "window closed" events to reset the hint on the desktopswitch buttons.

Proposed solution: the implementation should listen to window close events and lookup whether an urgency hint was registered in the desktopswitch plugin for that window id and if so, clear it.

##### Steps to Reproduce (for bugs)

Reproduction requirements: `wmctrl` and `zenity` packages are installed.

1. Have at least 2 workspaces (virtual desktops) configured.
2. Switch to desktop 2.
3. Execute:
    ```
    zenity --info --title urgent_demo --text urgent &
    ```
    (the `&` is crucial, the zenity window needs to be decoupled from the terminal parent)
4. Switch to desktop 1.
5. Execute:
    ```
    wmctrl -r "urgent_demo" -b add,demands_attention
    ```
    (observation: the desktopswitch's button for desktop 2 shows the urgent highlight)
6. Still on desktop 1, execute:
    ```
    killall zenity
    ```
7. Switch to desktop 2 and then back to desktop 1.

Observe that the urgent highlight of the button for desktop 2 on the desktopswitch plugin is stuck until lxqt-panel is restarted.

##### Context

I don't know which programs trigger this but I often experience stuck urgency hints on my lxqt-panel's desktopswitch widget over time and cannot get rid of them unless I restart lxqt-panel using the lxqt-config-session dialog. I rarely log out or restart due to using standby regularly. This means, these stuck urgency highlights on the desktopswitch buttons will never clear themselves. This defeats their purpose since it always seems like there is something demanding my attention when there isn't.

##### System Information

* LXQt Version: 1.2.0
* Distribution & Version: Debian GNU/Linux 12 (bookworm)
* Qt Version: 5.15.8
* liblxqt Version: 1.2.0

**Comment by M4he** [comment] 2023-07-23 08:51
> ##### Context
>
> I don't know which programs trigger this [...]

FWIW, I think Thunderbird's calendar reminder popups are often the culprit here. They spawn with an urgent hint but if you do not react to them for a while (either postpone or confirm), they will disappear themselves and reappear as a reminder later on.

**Comment by M4he** [comment] 2023-07-25 18:54
Tinkering with the source code a bit, I came up with the following prototype implementation that seems to fix the issue. Note that according to my observations, `KWindowInfo info = KWindowInfo(id, NET::WMDesktop | NET::WMState)` like used in `onWindowChanged` does not return correct information about the window here (e.g. `info.desktop()` does not return the correct number). This is most likely due to the event being emitted when the window is already gone along with that information. For that reason I resorted to simply iterating over all desktop buttons instead.


```diff
diff -ur lxqt-panel-1.2.1.orig/plugin-desktopswitch/desktopswitch.cpp lxqt-panel-1.2.1/plugin-desktopswitch/desktopswitch.cpp
--- lxqt-panel-1.2.1.orig/plugin-desktopswitch/desktopswitch.cpp	2023-01-02 12:39:43.000000000 +0100
+++ lxqt-panel-1.2.1/plugin-desktopswitch/desktopswitch.cpp	2023-07-25 20:45:00.598169481 +0200
@@ -73,6 +73,7 @@
 
     connect(KWindowSystem::self(), static_cast<void (KWindowSystem::*)(WId, NET::Properties, NET::Properties2)>(&KWindowSystem::windowChanged),
             this, &DesktopSwitch::onWindowChanged);
+    connect(KWindowSystem::self(), &KWindowSystem::windowRemoved, this, &DesktopSwitch::onWindowRemoved);
 }
 
 void DesktopSwitch::registerShortcuts()
@@ -131,6 +132,17 @@
     }
 }
 
+void DesktopSwitch::onWindowRemoved(WId id)
+{
+    const QList<QAbstractButton*> btns = m_buttons->buttons();
+    const int btn_count = btns.count();
+    for (int i = 0; i < btn_count; ++i)
+    {
+        DesktopSwitchButton * button = qobject_cast<DesktopSwitchButton*>(btns[i]);
+        button->setUrgencyHint(id, false);
+    }
+}
+
 void DesktopSwitch::refresh()
 {
     const QList<QAbstractButton*> btns = m_buttons->buttons();
diff -ur lxqt-panel-1.2.1.orig/plugin-desktopswitch/desktopswitch.h lxqt-panel-1.2.1/plugin-desktopswitch/desktopswitch.h
--- lxqt-panel-1.2.1.orig/plugin-desktopswitch/desktopswitch.h	2023-01-02 12:39:43.000000000 +0100
+++ lxqt-panel-1.2.1/plugin-desktopswitch/desktopswitch.h	2023-07-25 18:02:43.626721950 +0200
@@ -98,6 +98,7 @@
     void registerShortcuts();
     void shortcutRegistered();
     void onWindowChanged(WId id, NET::Properties properties, NET::Properties2 properties2);
+    void onWindowRemoved(WId id);
 };
 
 class DesktopSwitchPluginLibrary: public QObject, public ILXQtPanelPluginLibrary

```

**Comment by tsujan** [comment] 2024-05-09 22:53
This should be investigated after https://github.com/lxqt/lxqt-panel/pull/2041 is merged. It happened to me — as if out of nowhere — when I changed KWin's policy for focus stealing prevention. The issue is inherited by the PR.

**Comment by tsujan** [comment] 2024-05-10 14:17
There's a very easy way of reproducing this bug under KWin:

 1. Check "Close on middle-click" in Task Manager Settings.
 2. Set the focus stealing prevention to "High" in KDE System Settings → Window Behavior.
 3. Open a text file with FeatherPad by clicking it in PCManFM-Qt. It won't have focus, and its containing virtual desktop gets an urgency hint in Switcher. Let it remain unfocused.
 4. Change the virtual desktop and close FeatherPad by middle clicking its task-bar icon.

Then, the urgency hint of Switcher will persist until the panel is restarted.

I hadn't noticed it because I didn't use an LXQt theme that showed the urgency hint of Switcher.

**Closed** 2024-09-09 14:32 UTC
Labels: bug
