### ISSUE TITLE
[Enhancement] Better looking for widgets with other Icon Themes

### ISSUE THREAD

**Issue by varlesh** [lxqt/lxqt-panel#1402] opened 2020-05-11 08:19 UTC
Hi LXQt Dev Team. I have some questions for customization widget icons...
As i know, you use Breeze style as default (theme style, icon theme & etc). But this limit development for other themes. Why? Because widgets icons adjusted with only Breeze icon theme.
Breeze:
![image](https://user-images.githubusercontent.com/8083855/81538183-ed422c80-935d-11ea-9a03-ecadb42cbac3.png)
Papirus:
![screen](https://user-images.githubusercontent.com/8083855/81538225-fc28df00-935d-11ea-97dc-a0d412559d8a.jpg)

Widgets used monochrome icons from Breeze (by default 16/22 px on KDE)
But it's very limited for development another icon themes - because icon theme used on another DE's too.

Also Plasma can use app icons for tray from Plasma Theme. But LXQt now use only appmenu or not?

How you looking use suffix `-panel` for this icons with fallback original icon?
Ok... here list some widgets icons:

- showdesktop - icon `user-desktop-panel` fallback `user-desktop`
- qlipper - have option for choose icon
- mount - icon `drive-removable-media-panel` fallback `drive-removable-media`
- networkmanager - ?
- colorpicker - icon `color-picker-panel` fallback `color-picker`
- networkmonitor - hardcoded to **qrc** (( Why not use knemo status icons from theme?
- dom - icon `preferences-plugin-panel` fallback `preferences-plugin`
- statusnotifier - not found icon name (but icon non-monochrome on Breeze too)
- directorymenu - icon `folder-panel `fallback `folder`

**Comment by tsujan** [comment] 2020-05-11 08:37
LXQt recommends Breeze but doesn't depend on it. Breeze's symbolic icons are most appropriate for small icons and they change color according to the active widget style, provided that you use a light panel with light widget themes and a dark panel with dark ones (otherwise, you could use a custom icon set for the panel -- that's possible in panel's config dialog).

Other KDE icon sets can use Breeze's structure: symbolic icons for small sizes and colored ones for big sizes. If they don't, nothing bad will happen.

qlipper and networkmanager are independent apps that don't belong to LXQt. statusnotifier is a space for apps to put their tray icons in it, so it doesn't have a separate icon on the panel.

I, for one, prefer not to use an artificial suffix like "-panel" for panel icons but other LXQt devs may have a different opinion.

All in all, I really don't understand what the problem is, especially when panel can have a custom icon set.

**Comment by tsujan** [comment] 2020-05-11 08:44
> Also Plasma can use app icons for tray from Plasma Theme. But LXQt now use only appmenu or not?

LXQt panel has a System Tray plugin for very old apps and a Status Notifier Plugin for the usual ones. You could safely forget about System Tray and remove it from your panel if your system is up-to-date enough. GTK apps may need a program (whose name I don't remember) to support Status Notifier but Status Notifier is the "new" standard for tray icons.

**Comment by varlesh** [comment] 2020-05-11 08:45
@tsujan How you say `Other KDE icon sets can use Breeze's structure` - it's limit development for other icon themes. Because we support Mate/XFCE/Gnome/LXDE and etc

For example, `preferences-plugin` - this icon can not be monochrome, because used on system settings on other DE's. I can draw this icon 16/22px as monochrome - but this will be bad looking on application menu (some menus used 16/22px) and this limit for darker theme - Dark panel, White Window

**Comment by tsujan** [comment] 2020-05-11 08:48
@varlesh 
Even gnome-icon-theme works with LXQt and its panel. LXQt a Qt-based DE; we recommend Breeze-like sets because they have a property not found in GTK icon sets (= stylesheets in their SVG symbolic icons). If that property doesn't exist in a set, nothing bad will happen.

Being monochrome isn't enough for having the above-mentioned property.

**Comment by varlesh** [comment] 2020-05-11 08:49
You mean color scheme CSS?

**Comment by tsujan** [comment] 2020-05-11 08:51
Yes, if you mean that inside SVG icons. GTK icon sets don't have and don't use it. They have another method for setting the color of symbolic icons, that neither LXQt nor KDE doesn't support.

**Comment by varlesh** [comment] 2020-05-11 08:54
I know about CSS & symbolic icons. It's different tools.
I want only make Papirus better for LXQt. Not seen problem used fallback icons for that:
- This not broken Breeze or other themes
- Icons can be monochrome
- more variation for customization
As example:
`mButton.setIcon(XdgIcon::fromTheme(QStringLiteral("color-picker-panel"), QStringLiteral("color-picker"), QStringLiteral("kcolorchooser")));`

**Comment by tsujan** [comment] 2020-05-11 09:00
Being monochrome isn't enough for using the following property:

![symbolic](https://user-images.githubusercontent.com/981076/81543315-23e26c00-938b-11ea-8c21-650e5f7757df.png)

Only sets that have appropriate stylesheets obey it -- Breeze is one of them.

GTK and Qt/KDE icon sets are different in other ways too but I'm sure you're familiar with these things.

**Comment by varlesh** [comment] 2020-05-11 09:06
No... I know about color scheme and this option. Papirus support KDE Color Scheme for monochrome icons. Now it's about another.
Widgets impossible used monochrome icons, because it's limited KDE Breeze icon theme structure only.
If i'm make Papirus as Breeze icon theme structure - it's broken on other DE's

**Comment by tsujan** [comment] 2020-05-11 09:09
> If i'm make Papirus as Breeze icon theme structure - it's broken on other DE's

You get something and lose something else ;) This is about the old difference between Qt and GTK. Any attempt at unifying their looks has its drawbacks -- although those drawbacks aren't disastrous.

**Comment by varlesh** [comment] 2020-05-11 09:12
How worked Plasma Widgets - widgets see icon on Plasma Theme, if icons not available on Plasma Theme, see icons on Icon Theme. For example, Klipper. I can make monochrome icon on Plasma Theme and colored (original) with ANY size. And this will be worked.

But LXQt not have this - icons see on only Icon Theme. And this limit development & customization because this icons used on another DE's, menus, settings and etc...

**Comment by varlesh** [comment] 2020-05-11 09:14
> You get something and lose something else ;) This is about the old difference between Qt and GTK. Any attempt at unifying their looks has its drawbacks -- although those drawbacks aren't disastrous.

But if you added `-panel `suffix you not lost anything )) But 3-d party theme developers will get a new opportunity

**Comment by tsujan** [comment] 2020-05-11 09:20
> widgets see icon on Plasma Theme, if icons not available on Plasma

LXQt doesn't have the concept of Plasma. Plasma may be good for a DE that doesn't avoid extra resource usage or cluttered codes but LXQt does.

> But if you added -panel suffix you not lost anything

I didn't close this issue but only told my opinion: I don't like cluttering codes in this way. After a while, such exceptions might pile up and result in an unmaintainable code..

As I said, other LXQt members might have a different opinion; hence, leaving this open for now.

**Comment by varlesh** [comment] 2020-05-12 03:20
@tsujan Sorry for disturb you again. How you think it's possible added support use icons from LXQt Theme (if available) for widgets?

**Comment by tsujan** [comment] 2020-05-12 05:16
> How you think it's possible added support use icons from LXQt Theme (if available) for widgets?

I didn't understand what you mean but, maybe, you get your answer after reading a short explanation:

An "LXQt theme" is a theme for LXQt Panel and LXQt Runner. It consists of *Qt style-sheets*, especially `lxqt-panel.qss` and `lxqt-runner.qss`. It can contain a few icons for a few widgets as well as some images but Panel takes its other icons from the activate icon set, like other apps.

If a style section is missing in `lxqt-panel.qss`, Panel will use the active widget style for its corresponding widget. For example, in the theme I use, `#MainMenu` is almost empty, so that Kvantum draws the main menu.

You could get familiar with the structure of LXQt themes by taking a look at `/usr/share/lxqt/themes/`. Themes can be installed under `~/.local/share/lxqt/themes/` too.

Everything about Qt style-sheets is explained in https://doc.qt.io/qt-5/stylesheet-reference.html

New LXQt themes will be welcome.

**Closed** 2020-05-13 06:26 UTC
Labels: question
