### ISSUE TITLE
[feature request] in task manager widget add ability to pin icons

### ISSUE THREAD

**Issue by librewish** [lxqt/lxqt-panel#960] opened 2019-02-02 15:43 UTC
having two icons on panel one from task manager one from quick launch takes double  the space on panel

and if i want to use panel as dock i cant 
as it looks odd

**Comment by tsujan** [comment] 2019-02-02 15:50
IMHO, this is a fair feature request, except for "as it looks odd" -- and provided that it's optional because there are other use cases that require separate icons.

There may be already open issues that say the same thing in other words.

**Comment by tsujan** [comment] 2019-02-02 15:53
Duplicate of https://github.com/lxqt/lxqt/issues/131. Apparently no one has had time to work on it.

**Closed by tsujan** 2019-02-02 15:53 UTC

**Comment by tsujan** [comment] 2019-02-02 15:55
Also. another issue, in which the word "pin" is used: https://github.com/lxqt/lxqt/issues/1262. In that case, there were no consensus about the meaning.
