### ISSUE TITLE
kbindicator

### ISSUE THREAD

**Issue by hubearth** [lxqt/lxqt-panel#1391] opened 2020-05-02 07:34 UTC
kbindicator seems to work, but, if ran in terminal, it shows a error message
`QString::arg: Argument missing: true, ca`
The last segment ("ca") is my keyboard layout.
The message is repeated about 50 times a second, so I guess it affects lxqt-panel performance.

This issue is on the last release (0.15.0) and I have not tried earlier versions, so I can't compare. 

I run on Archlinux 
* Kernel : 5.6.8
* Qt Version: 5.14.2-2
* liblxqt Version: 0.15.0
* lxqt-build-tools Version: 0.7.0
* Package version: 0.15.0

**Comment by yan12125** [comment] 2020-05-02 08:39
"true" is from here:

https://github.com/lxqt/lxqt-panel/blob/40bbe83fded7af4c2e234d93c123d1636a06caee/plugin-kbindicator/src/settings.cpp#L57

How about using the path to Debian's [iso-flags-svg](https://tracker.debian.org/pkg/iso-flags-svg) as the default value for `layout_flag_pattern`? It's tested (https://github.com/lxqt/lxqt-panel/pull/1282#issue-340726110) and simple to install.

/cc @palinek

**Comment by tsujan** [comment] 2020-05-02 09:17
Yes, the bug is new and is probably caused by a copy-paste typo in the flag support implementation but the message is shown only on changing the keyboard, not 50 times a second.

**Comment by tsujan** [comment] 2020-05-02 09:29
BTW, I hadn't tried the flags implementation before. It works like a charm. This is just a minor issue.

**Comment by Willi-Smith** [comment] 2020-05-02 17:11
In my case this bug is even more annoying. Journalctl is flooded even more often. So far I removed the plugin from panel.
https://justpaste.it/2qk1e

**Comment by tsujan** [comment] 2020-05-02 18:46
Just change `true` to `%1` in the line-edit until it's fixed in the code.

**Comment by tsujan** [comment] 2020-05-03 18:37
Will be fixed in https://github.com/lxqt/lxqt-panel/pull/1398 and make the panel need a point release.

**Comment by hubearth** [comment] 2020-05-03 19:55
Thanks for the fast answer.
@tsujan , what do you mean by "the line-edit"?
My C++ really rusty, sorry for noob question. I did tried to change line 57 from `true` to `%1`, but it wouldn't compile. Changing it to `1` has no result as it seems to be interpreted as `true`.

As of @Willi-Smith, the bug has really annoying outputs in journalctl.

**Comment by hubearth** [comment] 2020-05-03 21:28
Thank you so much for the fast reply and . 
I applied f

**Closed** 2020-05-03 21:31 UTC
Labels: bug

**Comment by tsujan** [comment] 2020-05-04 02:46
@hubearth 
Thanks for testing the PR! I merged it.

In future, please don't close an issue that has a PR. It'll be closed automatically when the PR is merged.
