### ISSUE TITLE
Mount plugin opens filelight instead of pcmanfm-qt

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1661] opened 2021-09-11 19:45 UTC
Clicking  the "removabile device" item which pops up when clicking the mount plugin icon filelight opens, and it's not set in `~/,config/*mimeapp.list`
![schermata-09-11-12-23-02](https://user-images.githubusercontent.com/10681413/132959373-657854f5-b63d-442b-96e9-cbbc1b976e0b.png)

Strange enough this occurs _only_ on debian and not on arch (both with git master).

In both system with filelight installed when creating a new user filelight is used as default filemanager (alfabetically as it's the first app associated with inode/directory?). 

##### Expected Behavior

Default file manager opens always
##### Current Behavior

When filelight is installed there is no way to open the listed device(s) in the file manager from the mount plugin.
##### Steps to Reproduce (for bugs)

1. Install  filelight 
2. create a new user, he will have filelight set as default file manager
3. Change it to pcmanfm-qt from "file associations"
4. Insert a pendrive, and try to open it also clicking the mount plugin and clicking the device listed above.

##### Context

An user on Telegram reported a similar story, using devuan filelight changed mimetype association in ~/.config/*mimeapps.list, this remembered me my issue here.
##### System Information

* Distribution & Version: debian bullseye; git master. In arch it's not reproducibile for me

**Comment by antis81** [comment] 2021-09-11 20:50
Please check LXQt version on bullseye. This should be fixed "upstream" in LXQt >=0.17.

**Comment by tsujan** [comment] 2021-09-11 20:54
@stefonarch 
As you may have guessed, I can't reproduce it in Manjaro, which isn't different from Arch. Is `libfile-mimeinfo-perl` installed on both Arch and Debian?

**Comment by tsujan** [comment] 2021-09-12 03:41
OK, this is what I think has happened:

The mount plugin uses the Qt method `QDesktopServices::openUrl()` to open a path. That method uses `xdg-open` (belonging to `xdg-utils`), whose LXQt section is very elementary: it just calls "the generic method", whose functioning highly depends on packages like `libfile-mimeinfo-perl`.

Years ago, we had a long discussion on what the LXQt section of `xdg-open` should be. I proposed using of `gio` first and, if it didn't exist, using of the generic method — almost like what DEs like Gnome and MATE do (see https://github.com/lxqt/lxqt/issues/1298). As far as I remember, @luis-pereira agreed but, for reasons unknown to me, it hasn't happened yet.

Since then, in all my apps, when I want to open a path, I first call `gio` directly and, only if it doesn't exist, I call `QDesktopServices::openUrl()`. That's an effective workaround for the current situation. The real solution that I propose is like before.

I think this can be closed. https://github.com/lxqt/lxqt/issues/1298 can't be re-opened because it was created when `xdg-open` was different from what it is today. However, we need an open issue, specifically about the above-mentioned situation.

**Comment by tsujan** [comment] 2021-09-12 04:14
Oh, sorry, now I remember everything :)

@luis-pereira had a plan for an LXQt mimetype utility. He finished his excellent job before LXQt 0.17 and created `qtxdg-mat` based on `GIO`, which is exactly what we need inside `xdg-open` — his work is in 0,17 — but `xdg-utils` still hasn't changed.

@luis-pereira,
Did you find time to send a patch to `xdg-utils` devs?

**Comment by stefonarch** [comment] 2021-09-12 06:00
> Please check LXQt version on bullseye. This should be fixed "upstream" in LXQt >=0.17.

As you can read: LXQt version is git master, major to 0.17.

**Comment by antis81** [comment] 2021-09-12 07:02
@stefonarch Sorry confused with another discussion.

**Comment by tsujan** [comment] 2021-09-12 14:10
> $ apt search libfile-mimeinfo-perl...

The problem will be solved, once for all, only if `qtxdg-mat` goes into `xdg-open`. However, here I have:

```
$ xdg-mime query default inode/directory
pcmanfm-qt.desktop

```
And
```
$ qtxdg-mat defapp inode/directory                                                                                   
pcmanfm-qt.desktop 
```
"xdg-mime query default..." is used in `xdg-open` for LXQt; the solution is using "qtxdg-mat defapp...". But both are the same for me.

**Comment by stefonarch** [comment] 2021-09-12 15:08
Same results on debian for both commands...
Nowhere else opens filelight ("open download folder" in browser or similar)

**Comment by tsujan** [comment] 2021-09-12 15:33
> Same results on debian for both commands...

Then a big, red question mark appears in my mind. What's the difference between Debian and Arch in this regard? The patched Qt versions in Arch (`+kde+rxyz`)? Or a missing package in Debian?

**Comment by stefonarch** [comment] 2021-09-12 17:53
I've no idea... I stumpled upon this months ago, then forgot and yesterday on telegram a similar thing showed up.
Another question that arises: when more than one applications with` MimeType=inode/directory;` are installed and a new user is created, why is filelight selected as default? If you cancel `inode/directory=pcmanfm-qt.desktop` in ~/config/*mimeapps.list filelight will appear as default filemanager, also in arch.

As reported in https://github.com/lxqt/lxqt-config/issues/767 installing filelight  is enough, no lines get added somewhere.
`

**Comment by tsujan** [comment] 2021-09-12 18:13
> ... why is filelight selected as default?

If the user hasn't set a default file manager, it'll be chosen for him from the list of desktop files that support `inode/directory`.

> Adding inode/directory=pcmanfm-qt.desktop in *mimeapps.list by default could prevent this.

That's what the file association dialog does. Maybe there's a misunderstanding here. Let's be more specific:

My interpretation of the problem was that, when you choose pcmanfm-qt as the default file manager in File Associations → Default Applications, the mount plugin uses filelight in Debian but pcmanfm-qt in Arch.

Now, I see that you say the problem is that filelight is the default file manager *when the user hasn't defined a default file manager yet*. That isn't a bug.

**Comment by stefonarch** [comment] 2021-09-12 19:07
There are 2 issues here, one is the mount plugin in debian only that uses always filelight, the other is that users will experience a change for the default file manager caused  by simply installing filelight.

> If the user hasn't set a default file manager, it'll be chosen for him from the list of desktop files that support `inode/directory`.

I wonder if this if done alphabetically, in arch there are filelight, pcmanfm-qt abnbd thunar for` MimeType=inode/directory;` 
I made a test: installing dolphin it will open instead of filelight now, in the mount plugin and appear by itself as default filemanager.
I don't know calling this a bug is correct, but just installing a filemanager or filelight should not remove pcmanf-qt as default FM, as it appears in the GUI also when nothing is specified in *mimeapps-list.

**Comment by tsujan** [comment] 2021-09-12 19:12
> I don't know if calling this a bug is correct

It isn't a bug and can happen with all mime type handlers. Unless you specifically set an app as the default app for a mime type, that mime type might be opened by another app if you install it.

**Comment by stefonarch** [comment] 2021-09-12 19:14
Ok, but somehow the mount plugin in debian follows always that logic ignoring any choice made, picking the _first one alphabetically_ which handles `MimeType=inode/directory;`

**Comment by tsujan** [comment] 2021-09-12 19:14
As for browsers, some of them (like Firefox) ask you how to open a mimetype. In other words, they may have their own list, instead of using the real default app. That's not good practice.

**Comment by tsujan** [comment] 2021-09-12 19:16
> Ok, but somehow the mount plugin in debian follows always that logic ignoring

But you said, in https://github.com/lxqt/lxqt-panel/issues/1661#issuecomment-917680875, "Adding inode/directory=pcmanfm-qt.desktop in *mimeapps.list by default could prevent this." I'm confused!

**Comment by stefonarch** [comment] 2021-09-12 19:31
> > Ok, but somehow the mount plugin in debian follows always that logic ignoring
> 
> But you said, in [#1661 (comment)](https://github.com/lxqt/lxqt-panel/issues/1661#issuecomment-917680875), "Adding inode/directory=pcmanfm-qt.desktop in *mimeapps.list by default could prevent this." I'm confused!

There I meant "...could prevent changing default filemanager just by installing it."
Sorry for the mixture of 2 somehow separate issues:

* installing filelight (or dolphin) changes default filemanager when nothing is set in *mimeapps.list
* switching to pcmanfm-qt in the GUI works, except for  mount plugin under debian and derivatives,  just tested for filelight and dolphin in Lubuntu 21.04 - same behavior, in mount plugin.

**Comment by tsujan** [comment] 2021-09-12 19:53
> installing filelight (or dolphin) changes default filemanager when nothing is set in *mimeapps.list

Not a bug. It's expected.

> switching to pcmanfm-qt in the GUI works, except for mount plugin under debian and derivatives,

Switching to pcmanfm-qt in the GUI is equivalent to setting it in `~.config/lxqt-mimeapps.list`. Please attach that file from Arch and also from Debian!

**Comment by stefonarch** [comment] 2021-09-12 20:02
I didn't find anything relevant there.
debian:
```
[Default Applications]
application/pdf=qpdfview.desktop
image/jpeg=lximage-qt.desktop
text/html=firefox-esr.desktop
x-scheme-handler/http=firefox-esr.desktop
x-scheme-handler/https=firefox-esr.desktop
x-scheme-handler/about=firefox-esr.desktop
x-scheme-handler/unknown=firefox-esr.desktop
image/png=lximage-qt.desktop
image/svg+xml=org.inkscape.Inkscape.desktop
application/epub+zip=calibre-ebook-viewer.desktop
text/plain=featherpad.desktop
text/markdown=featherpad.desktop
inode/directory=pcmanfm-qt.desktop

```

Arch tomorrow.

**Comment by tsujan** [comment] 2021-09-12 20:12
> Arch tomorrow.

No need for it.

With the info gathered on this page, the only things that come to my mind are these:

 * In Debian, packages are split artificially (= not intended by the original developers), so that you may not have everything that you have in Arch. Either that or,
 * There's a difference between the patched Qt in Arch and Debian's Qt. KDE devs backport the changes Qt devs make to Qt5 but don't release them in their open-source branch; Arch packages them.

**Comment by tsujan** [comment] 2021-09-12 22:28
OK, I found the cause, beyond any doubt. It was the same thing that I explained from start.

It's a little complicated; so, please bear with me. I verified it by testing with FeatherPad's code and also by using the mount plugin.

I have this line in `~/.local/share/applications/defaults.list`:
```
inode/directory=pcmanfm-qt.desktop
```
When I remove it, `QDesktopServices::openUrl()` opens all local directories in pcmanfm-qt, as it should. But it opens `/run/media/pedram/Transcend` (mounted USB flash) in Filelight. So weird!

It "sees" `/run/media/pedram/Transcend` as `inode/mount-point`. However, I have `/usr/share/mime/inode/mount-point.xml`, which contains this line:
```
<sub-class-of type="inode/directory"/>
```
So, `QDesktopServices::openUrl()` should open `/run/media/pedram/Transcend` in pcmanfm-qt but it doesn't. Why? The answer is in https://github.com/lxqt/lxqt-panel/issues/1661#issuecomment-917544373 and its following comment.

To prove my hypothesis, I replaced the block of `open_lxqt()` inside `/usr/bin/xdg-open` with this (just for testing and temporarily — it isn't good as a patch):

```bash
open_lxqt()
{
    local file="$(file_url_to_path "$1")"
    qtxdg-mat open "$file"
    if [ $? -eq 0 ]; then
        exit_success
    else
        exit_failure_operation_failed
    fi
}
```

Then, with or without `~/.local/share/applications/defaults.list`, the mount plugin opened the USB flash in pcmanfm-qt :)

**We need to send an LXQt patch to xdg-utils devs**.

**Comment by tsujan** [comment] 2021-09-12 22:41
I opened https://github.com/lxqt/libqtxdg/issues/264. Closing this...

**Closed by tsujan** 2021-09-12 22:41 UTC

**Comment by stefonarch** [comment] 2021-09-13 06:51
> OK, I found the cause, beyond any doubt. It was the same thing that I explained from start.

Good, but I still fail to understand why arch and derivatives aren't affected by this.

**Comment by tsujan** [comment] 2021-09-13 06:59
> why arch and derivatives aren't affected by this.

They *are* affected. Only by chance, I had that line in `~/.local/share/applications/defaults.list`. Once I removed it, I was able to see the issue first hand.

**Comment by tsujan** [comment] 2021-09-13 07:15
Oh, I forgot to say that `~/.local/share/applications/defaults.list` is deprecated. Most DEs avoid the mess; we need to do the same thing by using @luis-pereira's tool in `/usr/bin/xdg-open`.

**Comment by stefonarch** [comment] 2021-09-13 12:03
> > why arch and derivatives aren't affected by this.
> 
> They _are_ affected. Only by chance, I had that line in `~/.local/share/applications/defaults.list`. Once I removed it, I was able to see the issue first hand.

Strange enough on arch I see now:
```
 $ cat /home/stef/.config/lxqt-mimeapps.list|grep inode
inode/directory=pcmanfm-qt.desktop
inode/mount-point=org.kde.filelight.desktop


$ cat /home/stef/.config/mimeapps.list|grep inode
inode/directory=pcmanfm-qt.desktop;org.kde.dolphin.desktop;org.kde.elisa.desktop;pcmanfm-qt-f.desktop;org.kde.filelight.desktop;kid3-qt.desktop;thunar.desktop;
inode/symlink=org.kde.ark.desktop;
inode/directory=pcmanfm-qt.desktop;
inode/symlink=org.kde.ark.desktop;
file/inode=thunar.desktop

```
but  pcmanfm-qt opens from mount plugin ...

`~/.local/share/mimeapps.list 
` is empty

**Comment by tsujan** [comment] 2021-09-13 13:49
There are more deprecated files (you didn't check `~/.local/share/applications/defaults.list`) and who knows which one causes a difference that shouldn't exist logically? The point is that `xdg-open` → `open_generic "$1"` is too poor and causes troubles like this.
