### ISSUE TITLE
[Feature request] Dynamic menu additions

### ISSUE THREAD

**Issue by ianfarrell47** [lxqt/lxqt-panel#1787] opened 2022-06-07 03:39 UTC
**Is your feature request related to a problem? Please describe.**
With lxqt-panel open, and after installing a new application with an XDG desktop menu entry, the correct icon is missing until restarting lxqt-panel. A menu entry for the newly installed program does appear, just with the "undefined" icon.

**Describe the solution you'd like**
lxqt-panel's menu queries the icon when it detects a new entry.
It would also be good if the menu GUI didn't close while updating for changed entries.

**Comment by tsujan** [comment] 2022-06-07 03:54
This is a known bug. Duplicate of https://github.com/lxqt/libqtxdg/issues/226

**Closed by tsujan** 2022-06-07 03:54 UTC
